services:

  keycloak:
    image: quay.io/keycloak/keycloak:26.7.1
    container_name: enterprise-keycloak

    command:
      - start-dev

    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

    ports:
      - "127.0.0.1:8080:8080"

    volumes:
      - keycloak_data:/opt/keycloak/data

  postgres:
    image: postgres:16
    container_name: orgshield-postgres

    environment:
      POSTGRES_DB: orgshield
      POSTGRES_USER: orgshield
      POSTGRES_PASSWORD: orgshield

    ports:
      - "5432:5432"

    volumes:
        - orgshield_postgres_data:/var/lib/postgresql/data

volumes:
    keycloak_data:
    orgshield_postgres_data: